[package]
name = "tamto-chord"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tamto-grpc = { version = "0.1.0", path = "../../libs/grpc" }
chord-rs = { version = "0.1.0", path = "../../libs/chord" }

async-trait = "0.1.67"
clap = { version = "4.1.13", features = ["derive"]}
tokio = { version = "1.27.0", features = ["rt-multi-thread", "macros", "time"] }
log = "0.4.17"
simplelog = "0.12.1"
