[package]
name = "chord-rs-cli"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "CLI tool to interact with a chord cluster, it's part of the chord-rs project"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chord-grpc = { version = "0.1.0", path = "../../libs/chord/grpc" }
chord-capnp = { version = "0.1.0", path = "../../libs/chord/capnp" }
chord-rs-core = { version = "0.1.0", path = "../../libs/chord/core" }

async-trait = "0.1.67"
clap = { version = "4.1.13", features = ["derive"]}
tokio = { version = "1.27.0", features = ["rt-multi-thread", "macros", "time"] }
log = "0.4.17"
simplelog = "0.12.1"
